# backend/Dockerfile

FROM python:3.11-slim

RUN apt update \
    && apt install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["python", "-m", "quart", "run", "--port=8000", "--host=127.0.0.1", "--reload"]
